### ISSUE TITLE
xdmcp being compiled despite explicitly being disabled in meson

### ISSUE THREAD

**Issue by kyx0r** [X11Libre/xserver#239]
### Select the version

25.0.0.1

### Describe your issue

```
  DDX
    Xorg             : YES
    Xnest            : YES
    Xvfb             : YES
    Xwin             : NO
    Xquartz          : NO

  User defined options
    default_font_path: /usr/share/fonts
    dri1             : true
    dri2             : true
    dri3             : true
    glamor           : true
    glx              : true
    localstatedir    : /var
    prefix           : /usr
    systemd_logind   : false
    warning_level    : 0
    xdmcp            : false   <---- this
    xephyr           : false
    xorg             : true

Found ninja-1.9 at /usr/bin/ninja
ninja: entering directory 'output'
```

Resulted in a build failure:

```
[474/638] Compiling C object os/liblibxserver_os.a.p/WaitFor.c.o
ninja: job failed: cc -Ios/liblibxserver_os.a.p -Ios -I../os -I. -I.. -IXext -I../Xext -IXi -I../Xi -Icomposite -I../composite -Idamageext -I../damageext -Iexa -I../exa -Ifb -I../fb -Iglamor -I../glamor -Imi -I../mi -Imiext/damage -I../miext/damage -Imiext/shadow -I../miext/shadow -Imiext/sync -I../miext/sync -Idbe -I../dbe -Idix -I../dix -Idri3 -I../dri3 -Iinclude -I../include -Ipresent -I../present -Irandr -I../randr -Irender -I../render -Ixfixes -I../xfixes -I/usr/include/X11/dri -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -std=gnu99 -O2 -g -DHAVE_DIX_CONFIG_H -fno-strict-aliasing -fvisibility=hidden -Wvla -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Wvla -O2 -fPIC -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -DCLIENTIDS -MD -MQ os/liblibxserver_os.a.p/xdmauth.c.o -MF os/liblibxserver_os.a.p/xdmauth.c.o.d -o os/liblibxserver_os.a.p/xdmauth.c.o -c ../os/xdmauth.c
In file included from ../os/xdmauth.c:49:
../os/xdmcp.h:6:32: error: unknown type name 'ARRAY8Ptr'
    6 | typedef Bool (*ValidatorFunc) (ARRAY8Ptr Auth, ARRAY8Ptr Data, int packet_type);
      |                                ^~~~~~~~~
../os/xdmcp.h:6:48: error: unknown type name 'ARRAY8Ptr'
    6 | typedef Bool (*ValidatorFunc) (ARRAY8Ptr Auth, ARRAY8Ptr Data, int packet_type);
      |                                                ^~~~~~~~~
../os/xdmcp.h:7:32: error: unknown type name 'ARRAY8Ptr'
    7 | typedef Bool (*GeneratorFunc) (ARRAY8Ptr Auth, ARRAY8Ptr Data, int packet_type);
      |                                ^~~~~~~~~
../os/xdmcp.h:7:48: error: unknown type name 'ARRAY8Ptr'
    7 | typedef Bool (*GeneratorFunc) (ARRAY8Ptr Auth, ARRAY8Ptr Data, int packet_type);
      |                                                ^~~~~~~~~
../os/xdmcp.h:25:34: error: unknown type name 'ValidatorFunc'
   25 |                                  ValidatorFunc Validator,
      |                                  ^~~~~~~~~~~~~
../os/xdmcp.h:26:34: error: unknown type name 'GeneratorFunc'
   26 |                                  GeneratorFunc Generator,
      |                                  ^~~~~~~~~~~~~
```

### Extra fields

- [ ] I have checked the existing [issues](https://github.com/X11Libre/xserver/issues)
- [ ] I have read the [Contributing Guidelines](https://github.com/X11Libre/xserver/blob/master/CONTRIBUTING.md)
- [ ] I'd like to work on this issue

**Comment by HaplessIdiot** [comment]
Update your ninja im on 1.12.1 and dont have any problems with building

I use

meson setup builddir --prefix=/usr
ninja -C builddir
sudo ninja -C builddir install

then reboot to test changes. Ive used those three lines MANY times trying to make personal security patches in my fork to resolve codeQL alerts that don't kill my fps in games. ive had beautiful rainbow artifacts and screenflashing its been really fun to test when i was trying to raise the max resolution of x to 65k

**Comment by kyx0r** [comment]
https://github.com/kyx0r/repo-main/blob/master/xorg/xlibre-server/build

Here is my build script. You did not specify -Dxdmcp as false in your test.
While I've also set mine to true and added the required dependency now, the build bug still stands.
My ninja is 1.2

**Comment by kyx0r** [comment]
Hm, there may be a hidden delta. My ninja is samurai, not the original C++ implementation. If you could please re-test this with -Dxdmcp set to false, thus narrowing it down to samurai incompatibility with original ninja.

However, please note that the same exact script works without any issues on the latest release from Xorg.

**Comment by callmetango** [comment]
Hello @kyx0r,

thank you for reporting the issue. Could you please update the description using the template given in https://github.com/X11Libre/misc/issues/133 ?

Please add your content in the template fields enclosed with `{{` and `}}` and remove the curly braces.

Could you please mark the checkboxes in the **Extra fields** section too by replacing the space ` ` with an `x`?

Thanks for your help.

**Comment by callmetango** [comment]
I can reproduce the issue when configuring the Meson build of the current Git version of the XLibre Xserver with:

```shell
meson setup build -Dxdmcp=false
```

**Comment by callmetango** [comment]
Found the corresponding patch at [Fix build with -Dxdmcp=false (52d71b02) · Commits · xorg / xserver · GitLab](https://gitlab.freedesktop.org/xorg/xserver/-/commit/52d71b025d2f45e08ff6110bc79e391f098272c0) and will create a pull request.

@metux How come this patch isn't in XLibre?

**Comment by metux** [comment]
> Found the corresponding patch at [Fix build with -Dxdmcp=false (52d71b02) · Commits · xorg / xserver · GitLab](https://gitlab.freedesktop.org/xorg/xserver/-/commit/52d71b025d2f45e08ff6110bc79e391f098272c0) and will create a pull request.
> 
> [@metux](https://github.com/metux) How come this patch isn't in XLibre?

It's a different issue: X11/Xdmcp.h needs to be included unconditionally here.

@kyx0r disabled xdmcp but not xdm-auth-1. 
Note that xdm-auth-1 can be used without xdmcp (but not very common)

**Comment by metux** [comment]
https://github.com/X11Libre/xserver/pull/488

**Comment by callmetango** [comment]
[#488](https://github.com/X11Libre/xserver/pull/488) for the `maint-25.0` branch and https://github.com/X11Libre/xserver/pull/489 for `master`.

**Comment by callmetango** [comment]
@metux
> > [@metux](https://github.com/metux) How come this patch isn't in XLibre?
> 
> It's a different issue: X11/Xdmcp.h needs to be included unconditionally here.
> 
> [@kyx0r](https://github.com/kyx0r) disabled xdmcp but not xdm-auth-1. Note that xdm-auth-1 can be used without xdmcp (but not very common)

So I can close https://github.com/X11Libre/xserver/pull/480?

**Comment by callmetango** [comment]
Resolved by the pull requests #488 and #489.

**Comment by callmetango** [comment]
Ps. Tried it myself and the successfully compiled the Xserver with:

```shell
meson setup build -Dxdmcp=false
```

**Comment by kyx0r** [comment]
@callmetango @metux 
Hello, thank you for addressing the issue. It is not entirely fixed. The #include must be conditional, otherwise you will get this error:
```
[467/639] Compiling C object os/libxserver_os.a.p/cmdline.c.o
ninja: job failed: cc -Ios/libxserver_os.a.p -Ios -I../os -I. -I.. -IXext -I../Xext -IXi -I../Xi -Icomposite -I../composite -Idamageext -I../damageext -Iexa -I../exa -Ifb -I../fb -Iglamor -I../glamor -Imi -I../mi -Imiext/damage -I../miext/damage -Imiext/shadow -I../miext/shadow -Imiext/sync -I../miext/sync -Idbe -I../dbe -Idix -I../dix -Idri3 -I../dri3 -Iinclude -I../include -Ipresent -I../present -Irandr -I../randr -Irender -I../render -Ixfixes -I../xfixes -I/usr/include/X11/dri -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -std=gnu99 -O2 -g -DHAVE_DIX_CONFIG_H -fno-strict-aliasing -fvisibility=hidden -Wvla -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Woverride-init -Wvla -O2 -fPIC -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -DCLIENTIDS -MD -MQ os/libxserver_os.a.p/xdmauth.c.o -MF os/libxserver_os.a.p/xdmauth.c.o.d -o os/libxserver_os.a.p/xdmauth.c.o -c ../os/xdmauth.c
In file included from ../os/xdmauth.c:49:
../os/xdmcp.h:4:10: fatal error: X11/Xdmcp.h: No such file or directory
    4 | #include <X11/Xdmcp.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by callmetango** [comment]
@kyx0r
Hmm, strange. Could you please post how you invoke your build of the Xserver?

**Comment by kyx0r** [comment]
If the point is to build without xdmcp, you cannot assume that the header will be present on a system.

I published a fix patch here:
https://github.com/kyx0r/repo-main/blob/master/xorg/xlibre-server/patches/noxdmcp.patch

The build script is here:
https://github.com/kyx0r/repo-main/blob/master/xorg/xlibre-server/build

Updated to 25.0.0.6 just now.

**Comment by callmetango** [comment]
@kyx0r I tried to reproduce the bug with the current Git master version and your script at [repo-main/xorg/xlibre-server/build at a398b3a7 · kyx0r/repo-main](https://github.com/kyx0r/repo-main/blob/a398b3a7522feb3adb62d2d8db4637179e59b3fb/xorg/xlibre-server/build) but without the patch [repo-main/xorg/xlibre-server/build at a398b3a7 · kyx0r/repo-main](https://github.com/kyx0r/repo-main/blob/a398b3a7522feb3adb62d2d8db4637179e59b3fb/xorg/xlibre-server/build). The build succeeds when using `meson` as well when using `muon`.

So I am unable to reproduce it.

**Comment by kyx0r** [comment]
I think there is a lack of understanding about the problem. You will be able to compile it if the said header is present on a system. Which means you have to make a condition when it is not, which may be distro / packaging specific. Typically package name is libXdmcp but may wary.

To verify that it is:
find / -name Xdmcp.h

Once it finds it, you can reproduce the issue manually and distro agnostic way by doing:

mv /usr/include/X11/Xdmcp.h /usr/include/X11/_Xdmcp.h

try building now, will fail.

Put it back like it was.
mv /usr/include/X11/_Xdmcp.h /usr/include/X11/Xdmcp.h

**Comment by kyx0r** [comment]
So, to reiterate:

Since -Dxdmcp=false, package maintainers should be able to drop the libXdmcp build dependency (which ultimately contains Xdmcp.h)

Right now this is not the case, since the include is not conditional like it should be.

Hope this helps,
K.

**Comment by callmetango** [comment]
> Since -Dxdmcp=false, package maintainers should be able to drop the libXdmcp build dependency (which ultimately contains Xdmcp.h)

Now I get it and will try to fix it.

**Comment by stefan11111** [comment]
@kyx0r See if this fixes the issue: https://github.com/X11Libre/xserver/pull/1096
